language: node_js

os: linux

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
  edge: true
